site_name: "M.Sc Mathematics Notes"
site_description: "Transcripts and Study Notes for M.Sc Mathematics (2025 Edition)"
site_author: "Deepak Nair"
site_url: "https://dhnair.github.io/msc-maths/"
repo_url: "https://github.com/dhnair/msc-maths"
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - content.code.annotate
    - content.tabs.link
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
    - scheme: slate
      primary: indigo
      accent: deep purple
  font:
    text: "Inter"
    code: "JetBrains Mono"
  icon:
    repo: fontawesome/brands/github

# Markdown extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - tables
  - footnotes

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - 📚 Resources:
      - References:
          - Intervals and Partitions: resources/references/intervals_and_partitions.md
          - Math Symbols Glossary: resources/references/math_symbols_glossary.md
          - Math Symbols Cheat Sheet: resources/references/math_symbols_cheat_sheet.md
      - Rules & Templates:
          - Transcript Formatting Guidelines: resources/rules/transcript_notes_formatting_guidelines.md
          - Transcript Template: resources/rules/transcript_template.md

  - 🧮 Term 1:
      - Real Analysis I:
          - Transcript: term1/real_analysis_i/transcripts/emth515_u01t01_transcript.md
          - Study Notes: term1/real_analysis_i/notes/emth515_u01t01_study_notes.md
      - Advanced Abstract Algebra I:
          - Transcript: term1/advanced_abstract_algebra_i/transcripts/emth516_u01_transcript.md
          - Study Notes: term1/advanced_abstract_algebra_i/notes/emth516_u01_study_notes.md
      - Fundamentals of Information Technology:
          - Transcript: term1/fundamentals_of_information_technology/transcripts/ecap145_u01l01_full_transcript.md
          - Study Notes: term1/fundamentals_of_information_technology/notes/ecap145_u01l01_study_notes.md

plugins:
  - search
  - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false

