// sidebars.js
const fs = require('fs');
const path = require('path');

// turn underscores into spaces and Title Case, but keep acronyms uppercase
function beautify(name) {
  return name
    .replace(/_/g, ' ') // underscores -> spaces
    .replace(/\b([a-z])(?=[a-z]+\b)/g, m => m.toUpperCase()) // Capitalize
    .replace(/\bEmth/g, 'EMTH')
    .replace(/\bEcap/g, 'ECAP');
}

function generateSidebar(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries
    .filter(e => e.isDirectory())
    .map(e => ({
      type: 'category',
      label: beautify(e.name),
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: path.relative('docs', path.join(dir, e.name)) }],
    }));
}

module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'M.Sc. Mathematics',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'references' },
        ...generateSidebar('docs/term1'),
      ],
    },
  ],
};
