// sidebars.js
module.exports = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'M.Sc. Mathematics',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: '.' },
      ],
    },
  ],
};
